## Create the Managed-fusion-agent Namespace
---
apiVersion: v1
kind: Namespace
metadata:
  name: managed-fusion
  labels:
    misf.ibm.com/managed: "true"
---

## Create the operator-group
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
 name: managed-fusion-og
 namespace: managed-fusion
spec:
 selector:
   matchLabels:
     misf.ibm.com/managed: "true"

---

## Create the catalog-source
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
 name: managed-fusion-catsrc
 namespace: managed-fusion
spec:
 sourceType: grpc
 image: quay.io/resoni/managed-fusion-agent-index:4.12.3-31.05
 displayName: Managed Fusion Agent

---

## Create the subscription
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
 name: managed-fusion
 namespace: managed-fusion
spec:
 channel: alpha
 name: managed-fusion-agent
 source: managed-fusion-catsrc
 sourceNamespace: managed-fusion

---

## Create the secret
---
